import type { Ingredient } from "@/lib/types";

// Conditionnements (packSize) + prix moyen HAUT du produit entier (packPrice, €).
// Prix calés sur des relevés Carrefour/Auchan 2024-2025 (prix affichés en rayon,
// hors promo). On vise volontairement la moyenne HAUTE : mieux vaut annoncer un
// budget légèrement surestimé qu'un budget trop optimiste que le client dépasse.
// Le priceFactor du magasin (0.84 discount → 1.38 bio) affine ensuite au calcul.
export const INGREDIENTS: Ingredient[] = [
  // ---------- Boucherie / Poissonnerie ----------
  { id: "chicken", name: "Blanc de poulet", aisle: "boucherie", baseUnit: "g", packSize: 1000, packLabel: "1 kg", packPrice: 12.5 },
  { id: "chicken_thigh", name: "Cuisse de poulet", aisle: "boucherie", baseUnit: "g", packSize: 1000, packLabel: "1 kg", packPrice: 8.5 },
  { id: "beef", name: "Bœuf haché 5%", aisle: "boucherie", baseUnit: "g", packSize: 500, packLabel: "barquette 500 g", packPrice: 6.9 },
  { id: "beef_steak", name: "Steak de bœuf", aisle: "boucherie", baseUnit: "g", packSize: 300, packLabel: "≈300 g (2 pièces)", packPrice: 7.5 },
  { id: "turkey", name: "Escalope de dinde", aisle: "boucherie", baseUnit: "g", packSize: 400, packLabel: "400 g", packPrice: 6.5 },
  { id: "merguez", name: "Merguez", aisle: "boucherie", baseUnit: "g", packSize: 400, packLabel: "400 g", packPrice: 5.5 },
  { id: "ham", name: "Jambon de dinde", aisle: "boucherie", baseUnit: "g", packSize: 200, packLabel: "200 g (tranches)", packPrice: 3.0 },
  { id: "salmon", name: "Filet de saumon", aisle: "boucherie", baseUnit: "g", packSize: 260, packLabel: "≈260 g (2 pavés)", packPrice: 8.9 },
  { id: "cod", name: "Filet de cabillaud", aisle: "boucherie", baseUnit: "g", packSize: 300, packLabel: "≈300 g (2 filets)", packPrice: 7.0 },
  { id: "shrimp", name: "Crevettes", aisle: "boucherie", baseUnit: "g", packSize: 200, packLabel: "200 g", packPrice: 5.9 },
  { id: "tuna_canned", name: "Thon en boîte", aisle: "epicerie", baseUnit: "g", packSize: 140, packLabel: "boîte 140 g", packPrice: 2.0 },
  { id: "sardines", name: "Sardines en boîte", aisle: "epicerie", baseUnit: "g", packSize: 120, packLabel: "boîte 120 g", packPrice: 2.0 },

  // ---------- Crémerie ----------
  { id: "eggs", name: "Œufs", aisle: "cremerie", baseUnit: "piece", packSize: 6, packLabel: "boîte de 6", packPrice: 2.9 },
  { id: "cheese", name: "Fromage râpé", aisle: "cremerie", baseUnit: "g", packSize: 200, packLabel: "sachet 200 g", packPrice: 2.9 },
  { id: "mozzarella", name: "Mozzarella", aisle: "cremerie", baseUnit: "g", packSize: 125, packLabel: "boule 125 g", packPrice: 1.5 },
  { id: "feta", name: "Feta", aisle: "cremerie", baseUnit: "g", packSize: 200, packLabel: "200 g", packPrice: 3.0 },
  { id: "parmesan", name: "Parmesan", aisle: "cremerie", baseUnit: "g", packSize: 100, packLabel: "100 g", packPrice: 3.2 },
  { id: "cream", name: "Crème fraîche", aisle: "cremerie", baseUnit: "ml", packSize: 200, packLabel: "pot 20 cl", packPrice: 1.5 },
  { id: "yogurt", name: "Yaourt grec", aisle: "cremerie", baseUnit: "g", packSize: 400, packLabel: "pot 400 g", packPrice: 2.4 },
  { id: "butter", name: "Beurre", aisle: "cremerie", baseUnit: "g", packSize: 250, packLabel: "plaquette 250 g", packPrice: 2.5 },
  { id: "milk", name: "Lait demi-écrémé", aisle: "cremerie", baseUnit: "ml", packSize: 1000, packLabel: "brique 1 L", packPrice: 1.2 },
  { id: "soy_milk", name: "Lait de soja", aisle: "cremerie", baseUnit: "ml", packSize: 1000, packLabel: "brique 1 L", packPrice: 2.0 },
  { id: "fromage_blanc", name: "Fromage blanc", aisle: "cremerie", baseUnit: "g", packSize: 500, packLabel: "pot 500 g", packPrice: 2.3 },
  { id: "halloumi", name: "Halloumi", aisle: "cremerie", baseUnit: "g", packSize: 225, packLabel: "225 g", packPrice: 3.6 },

  // ---------- Fruits & Légumes ----------
  { id: "potato", name: "Pommes de terre", aisle: "fruits_legumes", baseUnit: "g", packSize: 1000, packLabel: "filet 1 kg", packPrice: 2.3 },
  { id: "sweet_potato", name: "Patate douce", aisle: "fruits_legumes", baseUnit: "g", packSize: 1000, packLabel: "1 kg", packPrice: 3.9 },
  { id: "broccoli", name: "Brocoli", aisle: "fruits_legumes", baseUnit: "g", packSize: 500, packLabel: "1 pièce ≈500 g", packPrice: 2.3 },
  { id: "cauliflower", name: "Chou-fleur", aisle: "fruits_legumes", baseUnit: "g", packSize: 800, packLabel: "1 pièce", packPrice: 3.0 },
  { id: "zucchini", name: "Courgette", aisle: "fruits_legumes", baseUnit: "g", packSize: 500, packLabel: "≈2 pièces", packPrice: 2.2 },
  { id: "eggplant", name: "Aubergine", aisle: "fruits_legumes", baseUnit: "g", packSize: 500, packLabel: "≈2 pièces", packPrice: 2.5 },
  { id: "bell_pepper", name: "Poivron", aisle: "fruits_legumes", baseUnit: "piece", packSize: 3, packLabel: "barquette x3", packPrice: 2.5 },
  { id: "onion", name: "Oignon", aisle: "fruits_legumes", baseUnit: "g", packSize: 1000, packLabel: "filet 1 kg", packPrice: 1.8 },
  { id: "garlic", name: "Ail", aisle: "fruits_legumes", baseUnit: "piece", packSize: 12, packLabel: "1 tête (≈12 gousses)", packPrice: 0.7 },
  { id: "ginger", name: "Gingembre", aisle: "fruits_legumes", baseUnit: "g", packSize: 100, packLabel: "morceau ≈100 g", packPrice: 1.5 },
  { id: "spinach", name: "Épinards frais", aisle: "fruits_legumes", baseUnit: "g", packSize: 200, packLabel: "sachet 200 g", packPrice: 2.2 },
  { id: "carrot", name: "Carottes", aisle: "fruits_legumes", baseUnit: "g", packSize: 1000, packLabel: "1 kg", packPrice: 1.8 },
  { id: "mushroom", name: "Champignons", aisle: "fruits_legumes", baseUnit: "g", packSize: 250, packLabel: "barquette 250 g", packPrice: 2.2 },
  { id: "tomato", name: "Tomates", aisle: "fruits_legumes", baseUnit: "g", packSize: 500, packLabel: "≈500 g", packPrice: 2.5 },
  { id: "cherry_tomato", name: "Tomates cerises", aisle: "fruits_legumes", baseUnit: "g", packSize: 250, packLabel: "barquette 250 g", packPrice: 2.5 },
  { id: "cucumber", name: "Concombre", aisle: "fruits_legumes", baseUnit: "piece", packSize: 1, packLabel: "1 pièce", packPrice: 1.1 },
  { id: "salad", name: "Salade verte", aisle: "fruits_legumes", baseUnit: "piece", packSize: 1, packLabel: "1 pièce", packPrice: 1.2 },
  { id: "avocado", name: "Avocat", aisle: "fruits_legumes", baseUnit: "piece", packSize: 2, packLabel: "filet x2", packPrice: 2.2 },
  { id: "lemon", name: "Citron", aisle: "fruits_legumes", baseUnit: "piece", packSize: 4, packLabel: "filet x4", packPrice: 1.7 },
  { id: "green_beans", name: "Haricots verts", aisle: "fruits_legumes", baseUnit: "g", packSize: 400, packLabel: "400 g", packPrice: 2.9 },
  { id: "banana", name: "Bananes", aisle: "fruits_legumes", baseUnit: "piece", packSize: 6, packLabel: "régime ≈6", packPrice: 1.7 },
  { id: "apple", name: "Pommes", aisle: "fruits_legumes", baseUnit: "piece", packSize: 6, packLabel: "filet ≈6", packPrice: 2.9 },
  { id: "leek", name: "Poireaux", aisle: "fruits_legumes", baseUnit: "g", packSize: 500, packLabel: "≈2-3 pièces", packPrice: 2.3 },
  { id: "cabbage", name: "Chou", aisle: "fruits_legumes", baseUnit: "g", packSize: 800, packLabel: "1 pièce", packPrice: 1.8 },
  { id: "butternut", name: "Courge butternut", aisle: "fruits_legumes", baseUnit: "g", packSize: 1000, packLabel: "≈1 kg", packPrice: 2.9 },
  { id: "pak_choi", name: "Pak choï", aisle: "fruits_legumes", baseUnit: "g", packSize: 400, packLabel: "≈2 pièces", packPrice: 2.5 },

  // ---------- Épicerie ----------
  { id: "tofu", name: "Tofu nature", aisle: "epicerie", baseUnit: "g", packSize: 200, packLabel: "bloc 200 g", packPrice: 2.2 },
  { id: "chickpeas", name: "Pois chiches", aisle: "epicerie", baseUnit: "g", packSize: 400, packLabel: "boîte 400 g", packPrice: 1.2 },
  { id: "red_beans", name: "Haricots rouges", aisle: "epicerie", baseUnit: "g", packSize: 400, packLabel: "boîte 400 g", packPrice: 1.2 },
  { id: "lentils", name: "Lentilles corail", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 2.8 },
  { id: "rice", name: "Riz basmati", aisle: "epicerie", baseUnit: "g", packSize: 1000, packLabel: "1 kg", packPrice: 3.5 },
  { id: "quinoa", name: "Quinoa", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 4.5 },
  { id: "bulgur", name: "Boulgour", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 2.3 },
  { id: "couscous", name: "Semoule de couscous", aisle: "epicerie", baseUnit: "g", packSize: 1000, packLabel: "1 kg", packPrice: 2.9 },
  { id: "pasta", name: "Pâtes", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 1.3 },
  { id: "gf_pasta", name: "Pâtes sans gluten", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 3.5 },
  { id: "noodles", name: "Nouilles", aisle: "epicerie", baseUnit: "g", packSize: 250, packLabel: "250 g", packPrice: 1.8 },
  { id: "oats", name: "Flocons d'avoine", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 1.8 },
  { id: "tomato_canned", name: "Tomates concassées", aisle: "epicerie", baseUnit: "g", packSize: 400, packLabel: "boîte 400 g", packPrice: 1.2 },
  { id: "coconut_milk", name: "Lait de coco", aisle: "epicerie", baseUnit: "ml", packSize: 400, packLabel: "boîte 400 ml", packPrice: 1.8 },
  { id: "olive_oil", name: "Huile d'olive", aisle: "epicerie", baseUnit: "ml", packSize: 1000, packLabel: "1 L", packPrice: 10.0 },
  { id: "soy_sauce", name: "Sauce soja", aisle: "epicerie", baseUnit: "ml", packSize: 250, packLabel: "250 ml", packPrice: 2.9 },
  { id: "curry_paste", name: "Pâte de curry", aisle: "epicerie", baseUnit: "g", packSize: 200, packLabel: "pot 200 g", packPrice: 4.5 },
  { id: "pesto", name: "Pesto", aisle: "epicerie", baseUnit: "g", packSize: 190, packLabel: "pot 190 g", packPrice: 3.0 },
  { id: "peanut_butter", name: "Beurre de cacahuète", aisle: "epicerie", baseUnit: "g", packSize: 350, packLabel: "pot 350 g", packPrice: 3.9 },
  { id: "honey", name: "Miel", aisle: "epicerie", baseUnit: "g", packSize: 250, packLabel: "pot 250 g", packPrice: 5.0 },
  { id: "black_beans", name: "Haricots noirs", aisle: "epicerie", baseUnit: "g", packSize: 400, packLabel: "boîte 400 g", packPrice: 1.3 },
  { id: "corn", name: "Maïs", aisle: "epicerie", baseUnit: "g", packSize: 285, packLabel: "boîte 285 g", packPrice: 1.2 },
  { id: "polenta", name: "Polenta", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "500 g", packPrice: 1.9 },
  { id: "gnocchi", name: "Gnocchi", aisle: "epicerie", baseUnit: "g", packSize: 500, packLabel: "sachet 500 g", packPrice: 2.3 },
  { id: "seitan", name: "Seitan", aisle: "epicerie", baseUnit: "g", packSize: 200, packLabel: "200 g", packPrice: 3.5 },
  { id: "chia", name: "Graines de chia", aisle: "epicerie", baseUnit: "g", packSize: 200, packLabel: "200 g", packPrice: 4.5 },
  { id: "almonds", name: "Amandes", aisle: "epicerie", baseUnit: "g", packSize: 200, packLabel: "200 g", packPrice: 3.5 },
  { id: "raisins", name: "Raisins secs", aisle: "epicerie", baseUnit: "g", packSize: 250, packLabel: "250 g", packPrice: 2.2 },

  // ---------- Boulangerie ----------
  { id: "bread", name: "Pain", aisle: "boulangerie", baseUnit: "piece", packSize: 1, packLabel: "1 pain", packPrice: 0.7 },
  { id: "wrap", name: "Galette / wrap", aisle: "boulangerie", baseUnit: "piece", packSize: 6, packLabel: "paquet de 6", packPrice: 2.3 },

  // ---------- Surgelé ----------
  { id: "frozen_veg", name: "Poêlée de légumes surgelés", aisle: "surgele", baseUnit: "g", packSize: 750, packLabel: "sachet 750 g", packPrice: 2.9 },
  { id: "peas", name: "Petits pois surgelés", aisle: "surgele", baseUnit: "g", packSize: 1000, packLabel: "sachet 1 kg", packPrice: 2.3 },
  { id: "berries", name: "Fruits rouges surgelés", aisle: "surgele", baseUnit: "g", packSize: 450, packLabel: "sachet 450 g", packPrice: 4.5 },
  { id: "edamame", name: "Édamame", aisle: "surgele", baseUnit: "g", packSize: 500, packLabel: "sachet 500 g", packPrice: 3.9 },
];
