import type { Recipe } from "@/lib/types";

// Catalogue curaté (FR/BE). Le moteur de matching y "cherche" les recettes
// adaptées (régime + équipement + type), une par jour. Pas de prix stocké :
// le coût est calculé depuis les ingrédients au prix du magasin (lib/pricing.ts).
//
// Rappel capacités : four=roast,bake,gratin,heat · airfryer=roast,fry,heat
//                    poele=fry,sear,simmer,heat · micro=heat,reheat,steam
export const RECIPES: Recipe[] = [
  {
    id: "r01", title: "Poulet rôti & légumes", emoji: "🍗",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 180, unit: "g" },
      { ingredientId: "potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r02", title: "Saumon vapeur express", emoji: "🐟",
    mealTypes: ["sain", "leger", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["steam"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "salmon", qtyPerServing: 150, unit: "g" },
      { ingredientId: "broccoli", qtyPerServing: 200, unit: "g" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
  },
  {
    id: "r03", title: "Curry de pois chiches", emoji: "🍛",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 25, defaultServings: 2,
    ingredients: [
      { ingredientId: "chickpeas", qtyPerServing: 150, unit: "g" },
      { ingredientId: "coconut_milk", qtyPerServing: 100, unit: "ml" },
      { ingredientId: "tomato_canned", qtyPerServing: 100, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "curry_paste", qtyPerServing: 20, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 80, unit: "g" },
    ],
  },
  {
    id: "r04", title: "Pâtes bolognaise", emoji: "🍝",
    mealTypes: ["proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "beef", qtyPerServing: 120, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 150, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
  },
  {
    id: "r05", title: "Buddha bowl quinoa", emoji: "🥗",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["heat"], prepMinutes: 20, defaultServings: 2,
    ingredients: [
      { ingredientId: "quinoa", qtyPerServing: 80, unit: "g" },
      { ingredientId: "chickpeas", qtyPerServing: 80, unit: "g" },
      { ingredientId: "spinach", qtyPerServing: 50, unit: "g" },
      { ingredientId: "bell_pepper", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
    ],
  },
  {
    id: "r06", title: "Gratin de courgettes", emoji: "🧀",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "sans_gluten"],
    reqCapabilities: ["gratin"], prepMinutes: 40, defaultServings: 2,
    ingredients: [
      { ingredientId: "zucchini", qtyPerServing: 250, unit: "g" },
      { ingredientId: "cheese", qtyPerServing: 60, unit: "g" },
      { ingredientId: "cream", qtyPerServing: 50, unit: "ml" },
      { ingredientId: "eggs", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r07", title: "Wrap poulet croustillant", emoji: "🌯",
    mealTypes: ["rapide", "proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 120, unit: "g" },
      { ingredientId: "wrap", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "bell_pepper", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "onion", qtyPerServing: 40, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
  },
  {
    id: "r08", title: "Omelette express", emoji: "🍳",
    mealTypes: ["rapide", "proteine", "leger"], dietTags: ["halal", "vege", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 10, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggs", qtyPerServing: 3, unit: "piece" },
      { ingredientId: "mushroom", qtyPerServing: 50, unit: "g" },
      { ingredientId: "spinach", qtyPerServing: 30, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
  },
  {
    id: "r09", title: "Dahl de lentilles corail", emoji: "🍲",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "lentils", qtyPerServing: 100, unit: "g" },
      { ingredientId: "coconut_milk", qtyPerServing: 80, unit: "ml" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 100, unit: "g" },
      { ingredientId: "curry_paste", qtyPerServing: 15, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 70, unit: "g" },
    ],
  },
  {
    id: "r10", title: "Patates douces rôties & tofu", emoji: "🍠",
    mealTypes: ["sain", "proteine"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 35, defaultServings: 2,
    ingredients: [
      { ingredientId: "sweet_potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "tofu", qtyPerServing: 120, unit: "g" },
      { ingredientId: "broccoli", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "soy_sauce", qtyPerServing: 10, unit: "ml" },
    ],
  },
  {
    id: "r11", title: "Steak haché & poêlée", emoji: "🥩",
    mealTypes: ["rapide", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["sear"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "beef", qtyPerServing: 150, unit: "g" },
      { ingredientId: "frozen_veg", qtyPerServing: 200, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
  },
  {
    id: "r12", title: "Riz sauté aux légumes", emoji: "🍚",
    mealTypes: ["rapide", "sain"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "frozen_veg", qtyPerServing: 150, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 15, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
  },
  {
    id: "r13", title: "Saumon rôti & quinoa", emoji: "🐟",
    mealTypes: ["sain", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 28, defaultServings: 2,
    ingredients: [
      { ingredientId: "salmon", qtyPerServing: 150, unit: "g" },
      { ingredientId: "quinoa", qtyPerServing: 80, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 100, unit: "g" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
  },
  {
    id: "r14", title: "Pâtes sans gluten aux légumes", emoji: "🍝",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 22, defaultServings: 2,
    ingredients: [
      { ingredientId: "gf_pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 100, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 120, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
  },
  {
    id: "r15", title: "Bowl poulet & riz (meal prep)", emoji: "🍗",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 35, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 160, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "broccoli", qtyPerServing: 120, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 80, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 10, unit: "ml" },
    ],
  },
  {
    id: "r16", title: "Soupe de légumes maison", emoji: "🥣",
    mealTypes: ["leger", "sain"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "carrot", qtyPerServing: 100, unit: "g" },
      { ingredientId: "potato", qtyPerServing: 120, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 80, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
  },
  {
    id: "r17", title: "Poulet tikka & riz", emoji: "🍛",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten"],
    reqCapabilities: ["roast"], prepMinutes: 35, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 170, unit: "g" },
      { ingredientId: "yogurt", qtyPerServing: 60, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
      { ingredientId: "curry_paste", qtyPerServing: 20, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r18", title: "Chili sin carne", emoji: "🌶️",
    mealTypes: ["sain", "proteine"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "red_beans", qtyPerServing: 120, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 150, unit: "g" },
      { ingredientId: "bell_pepper", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 80, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r19", title: "Saumon teriyaki & nouilles", emoji: "🍜",
    mealTypes: ["proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["sear"], prepMinutes: 22, defaultServings: 2,
    ingredients: [
      { ingredientId: "salmon", qtyPerServing: 150, unit: "g" },
      { ingredientId: "noodles", qtyPerServing: 100, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 20, unit: "ml" },
      { ingredientId: "broccoli", qtyPerServing: 100, unit: "g" },
      { ingredientId: "ginger", qtyPerServing: 10, unit: "g" },
    ],
  },
  {
    id: "r20", title: "Couscous végétarien", emoji: "🥘",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "couscous", qtyPerServing: 90, unit: "g" },
      { ingredientId: "chickpeas", qtyPerServing: 80, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 100, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 80, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 80, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
    ],
  },
  {
    id: "r21", title: "Œufs brouillés & toast avocat", emoji: "🥑",
    mealTypes: ["rapide", "leger"], dietTags: ["halal", "vege", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 12, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggs", qtyPerServing: 3, unit: "piece" },
      { ingredientId: "avocado", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "bread", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
  },
  {
    id: "r22", title: "Bowl pois chiches rôtis", emoji: "🥗",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "chickpeas", qtyPerServing: 120, unit: "g" },
      { ingredientId: "sweet_potato", qtyPerServing: 150, unit: "g" },
      { ingredientId: "spinach", qtyPerServing: 50, unit: "g" },
      { ingredientId: "cucumber", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
    ],
  },
  {
    id: "r23", title: "Gratin de chou-fleur", emoji: "🧀",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "sans_gluten"],
    reqCapabilities: ["gratin"], prepMinutes: 40, defaultServings: 2,
    ingredients: [
      { ingredientId: "cauliflower", qtyPerServing: 250, unit: "g" },
      { ingredientId: "cheese", qtyPerServing: 60, unit: "g" },
      { ingredientId: "cream", qtyPerServing: 60, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r24", title: "Pâtes pesto & tomates cerises", emoji: "🍝",
    mealTypes: ["rapide", "sain"], dietTags: ["halal", "vege"],
    reqCapabilities: ["simmer"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "pesto", qtyPerServing: 30, unit: "g" },
      { ingredientId: "cherry_tomato", qtyPerServing: 100, unit: "g" },
      { ingredientId: "parmesan", qtyPerServing: 15, unit: "g" },
    ],
  },
  {
    id: "r25", title: "Cabillaud rôti & légumes", emoji: "🐟",
    mealTypes: ["sain", "leger", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 28, defaultServings: 2,
    ingredients: [
      { ingredientId: "cod", qtyPerServing: 150, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 120, unit: "g" },
      { ingredientId: "cherry_tomato", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r26", title: "Wok de tofu & légumes", emoji: "🥡",
    mealTypes: ["sain", "rapide"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "tofu", qtyPerServing: 150, unit: "g" },
      { ingredientId: "frozen_veg", qtyPerServing: 200, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 20, unit: "ml" },
      { ingredientId: "ginger", qtyPerServing: 10, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 80, unit: "g" },
    ],
  },
  {
    id: "r27", title: "Tortilla de pommes de terre", emoji: "🍳",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "vege", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 25, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggs", qtyPerServing: 4, unit: "piece" },
      { ingredientId: "potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
  },
  {
    id: "r28", title: "Soupe de lentilles", emoji: "🍲",
    mealTypes: ["leger", "sain"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "lentils", qtyPerServing: 100, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 100, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 80, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
  },
  {
    id: "r29", title: "Burger maison & potatoes", emoji: "🍔",
    mealTypes: ["proteine"], dietTags: ["halal"],
    reqCapabilities: ["roast"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "beef", qtyPerServing: 150, unit: "g" },
      { ingredientId: "bread", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "cheese", qtyPerServing: 20, unit: "g" },
      { ingredientId: "potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "tomato", qtyPerServing: 50, unit: "g" },
    ],
  },
  {
    id: "r30", title: "Curry de légumes & riz", emoji: "🍛",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 28, defaultServings: 2,
    ingredients: [
      { ingredientId: "frozen_veg", qtyPerServing: 200, unit: "g" },
      { ingredientId: "coconut_milk", qtyPerServing: 120, unit: "ml" },
      { ingredientId: "curry_paste", qtyPerServing: 20, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
    ],
  },
  {
    id: "r31", title: "Salade de quinoa & feta", emoji: "🥗",
    mealTypes: ["leger", "sain"], dietTags: ["halal", "vege", "sans_gluten"],
    reqCapabilities: ["heat"], prepMinutes: 20, defaultServings: 2,
    ingredients: [
      { ingredientId: "quinoa", qtyPerServing: 90, unit: "g" },
      { ingredientId: "feta", qtyPerServing: 50, unit: "g" },
      { ingredientId: "cucumber", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "cherry_tomato", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
    ],
  },
  {
    id: "r32", title: "Porridge protéiné", emoji: "🥣",
    mealTypes: ["rapide", "leger"], dietTags: ["halal", "vege", "sans_lactose"],
    reqCapabilities: ["heat"], prepMinutes: 8, defaultServings: 2,
    ingredients: [
      { ingredientId: "oats", qtyPerServing: 80, unit: "g" },
      { ingredientId: "peanut_butter", qtyPerServing: 20, unit: "g" },
      { ingredientId: "honey", qtyPerServing: 15, unit: "g" },
    ],
  },
  {
    id: "r33", title: "Crevettes sautées & riz", emoji: "🍤",
    mealTypes: ["proteine", "leger"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "shrimp", qtyPerServing: 120, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 2, unit: "piece" },
      { ingredientId: "green_beans", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
  },
  {
    id: "r34", title: "Aubergines rôties & boulgour", emoji: "🍆",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 32, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggplant", qtyPerServing: 250, unit: "g" },
      { ingredientId: "bulgur", qtyPerServing: 90, unit: "g" },
      { ingredientId: "tomato", qtyPerServing: 80, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
  },
  {
    id: "r35", title: "Thon & pâtes express", emoji: "🐟",
    mealTypes: ["rapide", "proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "tuna_canned", qtyPerServing: 100, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 120, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 40, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
  },
  {
    id: "r36", title: "Dinde grillée & purée patate douce", emoji: "🦃",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["sear"], prepMinutes: 25, defaultServings: 2,
    ingredients: [
      { ingredientId: "turkey", qtyPerServing: 150, unit: "g" },
      { ingredientId: "sweet_potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "green_beans", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
  },
];
