import type { Recipe } from "@/lib/types";

// Catalogue curaté (FR/BE). Le moteur "cherche" les recettes adaptées (régime +
// équipement + type), une par jour. Pas de prix stocké : calculé depuis les
// ingrédients au prix du magasin (lib/pricing.ts). Chaque recette a ses étapes.
//
// Rappel capacités : four=roast,bake,gratin,heat · airfryer=roast,fry,heat
//                    poele=fry,sear,simmer,heat · micro=heat,reheat,steam
export const RECIPES: Recipe[] = [
  {
    id: "r01", title: "Poulet rôti & légumes", emoji: "🍗",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 180, unit: "g" },
      { ingredientId: "potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Préchauffer le four (ou l'Air Fryer) à 200°C.",
      "Couper pommes de terre et carottes en morceaux, émincer l'ail.",
      "Mélanger les légumes et le poulet avec l'huile d'olive, saler et poivrer.",
      "Enfourner 30 min en remuant à mi-cuisson, jusqu'à ce que le poulet soit doré.",
    ],
  },
  {
    id: "r02", title: "Saumon vapeur express", emoji: "🐟",
    mealTypes: ["sain", "leger", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["steam"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "salmon", qtyPerServing: 150, unit: "g" },
      { ingredientId: "broccoli", qtyPerServing: 200, unit: "g" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
    steps: [
      "Détailler le brocoli en bouquets.",
      "Déposer saumon et brocoli dans un plat adapté au micro-ondes avec un filet d'eau.",
      "Couvrir et cuire 6 à 8 min à pleine puissance.",
      "Arroser de jus de citron et d'huile d'olive avant de servir.",
    ],
  },
  {
    id: "r03", title: "Curry de pois chiches", emoji: "🍛",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 25, defaultServings: 2,
    ingredients: [
      { ingredientId: "chickpeas", qtyPerServing: 150, unit: "g" },
      { ingredientId: "coconut_milk", qtyPerServing: 100, unit: "ml" },
      { ingredientId: "tomato_canned", qtyPerServing: 100, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "curry_paste", qtyPerServing: 20, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 80, unit: "g" },
    ],
    steps: [
      "Faire revenir l'oignon émincé dans un peu d'huile.",
      "Ajouter la pâte de curry, puis les pois chiches égouttés et les tomates.",
      "Verser le lait de coco et laisser mijoter 15 min.",
      "Servir avec le riz cuit à l'eau.",
    ],
  },
  {
    id: "r04", title: "Pâtes bolognaise", emoji: "🍝",
    mealTypes: ["proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "beef", qtyPerServing: 120, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 150, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
    steps: [
      "Faire revenir l'oignon, ajouter le bœuf haché et le saisir.",
      "Ajouter les tomates concassées et laisser mijoter 20 min.",
      "Cuire les pâtes al dente dans l'eau bouillante salée.",
      "Mélanger pâtes et sauce, puis servir.",
    ],
  },
  {
    id: "r05", title: "Buddha bowl quinoa", emoji: "🥗",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["heat"], prepMinutes: 20, defaultServings: 2,
    ingredients: [
      { ingredientId: "quinoa", qtyPerServing: 80, unit: "g" },
      { ingredientId: "chickpeas", qtyPerServing: 80, unit: "g" },
      { ingredientId: "spinach", qtyPerServing: 50, unit: "g" },
      { ingredientId: "bell_pepper", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
    ],
    steps: [
      "Cuire le quinoa 12 min à l'eau bouillante, puis égoutter.",
      "Égoutter les pois chiches, couper le poivron.",
      "Disposer quinoa, pois chiches, épinards et poivron dans un bol.",
      "Assaisonner d'huile d'olive et de jus de citron.",
    ],
  },
  {
    id: "r06", title: "Gratin de courgettes", emoji: "🧀",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "sans_gluten"],
    reqCapabilities: ["gratin"], prepMinutes: 40, defaultServings: 2,
    ingredients: [
      { ingredientId: "zucchini", qtyPerServing: 250, unit: "g" },
      { ingredientId: "cheese", qtyPerServing: 60, unit: "g" },
      { ingredientId: "cream", qtyPerServing: 50, unit: "ml" },
      { ingredientId: "eggs", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Préchauffer le four à 190°C.",
      "Émincer les courgettes et l'ail, disposer dans un plat.",
      "Battre l'œuf avec la crème, verser sur les courgettes et couvrir de fromage.",
      "Enfourner 30 min jusqu'à ce que le gratin soit doré.",
    ],
  },
  {
    id: "r07", title: "Wrap poulet croustillant", emoji: "🌯",
    mealTypes: ["rapide", "proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 120, unit: "g" },
      { ingredientId: "wrap", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "bell_pepper", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "onion", qtyPerServing: 40, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
    steps: [
      "Couper le poulet en lamelles, émincer poivron et oignon.",
      "Poêler le poulet à l'huile jusqu'à coloration, ajouter les légumes.",
      "Garnir la galette de la préparation.",
      "Rouler le wrap et le saisir 1 min de chaque côté.",
    ],
  },
  {
    id: "r08", title: "Omelette express", emoji: "🍳",
    mealTypes: ["rapide", "proteine", "leger"], dietTags: ["halal", "vege", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 10, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggs", qtyPerServing: 3, unit: "piece" },
      { ingredientId: "mushroom", qtyPerServing: 50, unit: "g" },
      { ingredientId: "spinach", qtyPerServing: 30, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
    steps: [
      "Battre les œufs, saler et poivrer.",
      "Faire suer champignons et épinards à l'huile.",
      "Verser les œufs et cuire à feu moyen.",
      "Plier l'omelette et servir.",
    ],
  },
  {
    id: "r09", title: "Dahl de lentilles corail", emoji: "🍲",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "lentils", qtyPerServing: 100, unit: "g" },
      { ingredientId: "coconut_milk", qtyPerServing: 80, unit: "ml" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 100, unit: "g" },
      { ingredientId: "curry_paste", qtyPerServing: 15, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 70, unit: "g" },
    ],
    steps: [
      "Faire revenir l'oignon, ajouter la pâte de curry.",
      "Ajouter lentilles, tomates et lait de coco.",
      "Mijoter 18 à 20 min jusqu'à ce que les lentilles soient fondantes.",
      "Servir avec le riz.",
    ],
  },
  {
    id: "r10", title: "Patates douces rôties & tofu", emoji: "🍠",
    mealTypes: ["sain", "proteine"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 35, defaultServings: 2,
    ingredients: [
      { ingredientId: "sweet_potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "tofu", qtyPerServing: 120, unit: "g" },
      { ingredientId: "broccoli", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "soy_sauce", qtyPerServing: 10, unit: "ml" },
    ],
    steps: [
      "Préchauffer le four ou l'Air Fryer à 200°C.",
      "Couper patates douces et tofu en cubes, arroser d'huile et de sauce soja.",
      "Rôtir 25 à 30 min en remuant.",
      "Ajouter le brocoli vapeur et servir.",
    ],
  },
  {
    id: "r11", title: "Steak haché & poêlée", emoji: "🥩",
    mealTypes: ["rapide", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["sear"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "beef", qtyPerServing: 150, unit: "g" },
      { ingredientId: "frozen_veg", qtyPerServing: 200, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
    steps: [
      "Saisir les steaks hachés à la poêle 2 à 3 min par face.",
      "Dans une autre poêle, faire revenir la poêlée de légumes à l'huile.",
      "Saler et poivrer.",
      "Dresser et servir.",
    ],
  },
  {
    id: "r12", title: "Riz sauté aux légumes", emoji: "🍚",
    mealTypes: ["rapide", "sain"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "frozen_veg", qtyPerServing: 150, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 15, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
    steps: [
      "Cuire le riz et le laisser tiédir.",
      "Faire sauter l'ail et les légumes surgelés à l'huile.",
      "Ajouter le riz et la sauce soja, sauter 5 min à feu vif.",
      "Servir bien chaud.",
    ],
  },
  {
    id: "r13", title: "Saumon rôti & quinoa", emoji: "🐟",
    mealTypes: ["sain", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 28, defaultServings: 2,
    ingredients: [
      { ingredientId: "salmon", qtyPerServing: 150, unit: "g" },
      { ingredientId: "quinoa", qtyPerServing: 80, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 100, unit: "g" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
    steps: [
      "Préchauffer le four à 200°C.",
      "Déposer le saumon et les courgettes, arroser d'huile et de citron.",
      "Rôtir 15 à 18 min.",
      "Servir avec le quinoa cuit.",
    ],
  },
  {
    id: "r14", title: "Pâtes sans gluten aux légumes", emoji: "🍝",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 22, defaultServings: 2,
    ingredients: [
      { ingredientId: "gf_pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 100, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 120, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
    steps: [
      "Cuire les pâtes sans gluten selon le paquet.",
      "Faire revenir l'ail et les courgettes, ajouter les tomates.",
      "Mijoter 10 min.",
      "Mélanger avec les pâtes et servir.",
    ],
  },
  {
    id: "r15", title: "Bowl poulet & riz (meal prep)", emoji: "🍗",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 35, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 160, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "broccoli", qtyPerServing: 120, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 80, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 10, unit: "ml" },
    ],
    steps: [
      "Préchauffer le four ou l'Air Fryer à 200°C.",
      "Rôtir le poulet avec un filet d'huile 20 à 25 min.",
      "Cuire le riz ; faire le brocoli et les carottes vapeur.",
      "Assembler le bowl et napper de sauce soja.",
    ],
  },
  {
    id: "r16", title: "Soupe de légumes maison", emoji: "🥣",
    mealTypes: ["leger", "sain"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "carrot", qtyPerServing: 100, unit: "g" },
      { ingredientId: "potato", qtyPerServing: 120, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 80, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
    steps: [
      "Éplucher et couper tous les légumes.",
      "Faire suer l'oignon à l'huile, ajouter les légumes et couvrir d'eau.",
      "Mijoter 25 min.",
      "Mixer et assaisonner.",
    ],
  },
  {
    id: "r17", title: "Poulet tikka & riz", emoji: "🍛",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten"],
    reqCapabilities: ["roast"], prepMinutes: 35, defaultServings: 2,
    ingredients: [
      { ingredientId: "chicken", qtyPerServing: 170, unit: "g" },
      { ingredientId: "yogurt", qtyPerServing: 60, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
      { ingredientId: "curry_paste", qtyPerServing: 20, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Mélanger yaourt, pâte de curry et ail ; y faire mariner le poulet 10 min.",
      "Préchauffer le four à 210°C.",
      "Rôtir le poulet 20 à 25 min.",
      "Servir avec le riz et l'oignon émincé.",
    ],
  },
  {
    id: "r18", title: "Chili sin carne", emoji: "🌶️",
    mealTypes: ["sain", "proteine"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "red_beans", qtyPerServing: 120, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 150, unit: "g" },
      { ingredientId: "bell_pepper", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 80, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Faire revenir oignon, poivron et ail.",
      "Ajouter haricots rouges et tomates, épicer.",
      "Mijoter 20 min.",
      "Servir avec le riz.",
    ],
  },
  {
    id: "r19", title: "Saumon teriyaki & nouilles", emoji: "🍜",
    mealTypes: ["proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["sear"], prepMinutes: 22, defaultServings: 2,
    ingredients: [
      { ingredientId: "salmon", qtyPerServing: 150, unit: "g" },
      { ingredientId: "noodles", qtyPerServing: 100, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 20, unit: "ml" },
      { ingredientId: "broccoli", qtyPerServing: 100, unit: "g" },
      { ingredientId: "ginger", qtyPerServing: 10, unit: "g" },
    ],
    steps: [
      "Saisir le saumon à la poêle, ajouter sauce soja et gingembre pour glacer.",
      "Cuire les nouilles.",
      "Faire sauter le brocoli.",
      "Mélanger nouilles, brocoli et saumon.",
    ],
  },
  {
    id: "r20", title: "Couscous végétarien", emoji: "🥘",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "couscous", qtyPerServing: 90, unit: "g" },
      { ingredientId: "chickpeas", qtyPerServing: 80, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 100, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 80, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 80, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
    ],
    steps: [
      "Faire revenir oignon, carottes et courgettes.",
      "Ajouter pois chiches et tomates, mijoter 15 min.",
      "Préparer la semoule (eau bouillante, couvrir 5 min).",
      "Servir le bouillon de légumes sur la semoule.",
    ],
  },
  {
    id: "r21", title: "Œufs brouillés & toast avocat", emoji: "🥑",
    mealTypes: ["rapide", "leger"], dietTags: ["halal", "vege", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 12, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggs", qtyPerServing: 3, unit: "piece" },
      { ingredientId: "avocado", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "bread", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 5, unit: "ml" },
    ],
    steps: [
      "Toaster le pain et écraser l'avocat dessus.",
      "Battre les œufs.",
      "Cuire les œufs brouillés à feu doux avec un peu d'huile.",
      "Servir sur le toast.",
    ],
  },
  {
    id: "r22", title: "Bowl pois chiches rôtis", emoji: "🥗",
    mealTypes: ["sain", "leger"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "chickpeas", qtyPerServing: 120, unit: "g" },
      { ingredientId: "sweet_potato", qtyPerServing: 150, unit: "g" },
      { ingredientId: "spinach", qtyPerServing: 50, unit: "g" },
      { ingredientId: "cucumber", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
    ],
    steps: [
      "Préchauffer le four à 200°C.",
      "Rôtir pois chiches et patate douce en cubes 25 min.",
      "Préparer épinards et concombre.",
      "Assembler le bol, arroser d'huile et de citron.",
    ],
  },
  {
    id: "r23", title: "Gratin de chou-fleur", emoji: "🧀",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "sans_gluten"],
    reqCapabilities: ["gratin"], prepMinutes: 40, defaultServings: 2,
    ingredients: [
      { ingredientId: "cauliflower", qtyPerServing: 250, unit: "g" },
      { ingredientId: "cheese", qtyPerServing: 60, unit: "g" },
      { ingredientId: "cream", qtyPerServing: 60, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Préchauffer le four à 190°C.",
      "Cuire le chou-fleur 8 min à l'eau, puis égoutter.",
      "Disposer dans un plat, napper de crème et d'ail, couvrir de fromage.",
      "Gratiner 20 min.",
    ],
  },
  {
    id: "r24", title: "Pâtes pesto & tomates cerises", emoji: "🍝",
    mealTypes: ["rapide", "sain"], dietTags: ["halal", "vege"],
    reqCapabilities: ["simmer"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "pesto", qtyPerServing: 30, unit: "g" },
      { ingredientId: "cherry_tomato", qtyPerServing: 100, unit: "g" },
      { ingredientId: "parmesan", qtyPerServing: 15, unit: "g" },
    ],
    steps: [
      "Cuire les pâtes al dente.",
      "Couper les tomates cerises en deux.",
      "Mélanger pâtes, pesto et tomates.",
      "Parsemer de parmesan.",
    ],
  },
  {
    id: "r25", title: "Cabillaud rôti & légumes", emoji: "🐟",
    mealTypes: ["sain", "leger", "proteine"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 28, defaultServings: 2,
    ingredients: [
      { ingredientId: "cod", qtyPerServing: 150, unit: "g" },
      { ingredientId: "zucchini", qtyPerServing: 120, unit: "g" },
      { ingredientId: "cherry_tomato", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Préchauffer le four à 200°C.",
      "Déposer cabillaud, courgettes et tomates cerises, ajouter ail et huile.",
      "Rôtir 15 à 18 min.",
      "Servir.",
    ],
  },
  {
    id: "r26", title: "Wok de tofu & légumes", emoji: "🥡",
    mealTypes: ["sain", "rapide"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "tofu", qtyPerServing: 150, unit: "g" },
      { ingredientId: "frozen_veg", qtyPerServing: 200, unit: "g" },
      { ingredientId: "soy_sauce", qtyPerServing: 20, unit: "ml" },
      { ingredientId: "ginger", qtyPerServing: 10, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 80, unit: "g" },
    ],
    steps: [
      "Couper le tofu en cubes et le saisir au wok.",
      "Ajouter les légumes et le gingembre, sauter à feu vif.",
      "Déglacer à la sauce soja.",
      "Servir avec le riz.",
    ],
  },
  {
    id: "r27", title: "Tortilla de pommes de terre", emoji: "🍳",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "vege", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 25, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggs", qtyPerServing: 4, unit: "piece" },
      { ingredientId: "potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
    steps: [
      "Émincer pommes de terre et oignon, cuire doucement à l'huile.",
      "Battre les œufs et y mélanger les pommes de terre.",
      "Cuire la tortilla à la poêle 5 min par face.",
      "Laisser tiédir et couper en parts.",
    ],
  },
  {
    id: "r28", title: "Soupe de lentilles", emoji: "🍲",
    mealTypes: ["leger", "sain"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "lentils", qtyPerServing: 100, unit: "g" },
      { ingredientId: "carrot", qtyPerServing: 100, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 60, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 80, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 1, unit: "piece" },
    ],
    steps: [
      "Faire revenir oignon, carottes et ail.",
      "Ajouter lentilles et tomates, couvrir d'eau.",
      "Mijoter 20 à 25 min.",
      "Mixer partiellement et assaisonner.",
    ],
  },
  {
    id: "r29", title: "Burger maison & potatoes", emoji: "🍔",
    mealTypes: ["proteine"], dietTags: ["halal"],
    reqCapabilities: ["roast"], prepMinutes: 30, defaultServings: 2,
    ingredients: [
      { ingredientId: "beef", qtyPerServing: 150, unit: "g" },
      { ingredientId: "bread", qtyPerServing: 1, unit: "piece" },
      { ingredientId: "cheese", qtyPerServing: 20, unit: "g" },
      { ingredientId: "potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "tomato", qtyPerServing: 50, unit: "g" },
    ],
    steps: [
      "Préchauffer le four à 200°C et rôtir les pommes de terre en quartiers 30 min.",
      "Former et saisir les steaks hachés.",
      "Toaster le pain, ajouter steak, fromage et tomate.",
      "Servir avec les potatoes.",
    ],
  },
  {
    id: "r30", title: "Curry de légumes & riz", emoji: "🍛",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "vegan", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 28, defaultServings: 2,
    ingredients: [
      { ingredientId: "frozen_veg", qtyPerServing: 200, unit: "g" },
      { ingredientId: "coconut_milk", qtyPerServing: 120, unit: "ml" },
      { ingredientId: "curry_paste", qtyPerServing: 20, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
    ],
    steps: [
      "Faire revenir l'oignon et ajouter la pâte de curry.",
      "Ajouter les légumes et le lait de coco.",
      "Mijoter 18 min.",
      "Servir avec le riz.",
    ],
  },
  {
    id: "r31", title: "Salade de quinoa & feta", emoji: "🥗",
    mealTypes: ["leger", "sain"], dietTags: ["halal", "vege", "sans_gluten"],
    reqCapabilities: ["heat"], prepMinutes: 20, defaultServings: 2,
    ingredients: [
      { ingredientId: "quinoa", qtyPerServing: 90, unit: "g" },
      { ingredientId: "feta", qtyPerServing: 50, unit: "g" },
      { ingredientId: "cucumber", qtyPerServing: 0.5, unit: "piece" },
      { ingredientId: "cherry_tomato", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
      { ingredientId: "lemon", qtyPerServing: 0.5, unit: "piece" },
    ],
    steps: [
      "Cuire le quinoa et le laisser refroidir.",
      "Couper concombre, tomates cerises et feta.",
      "Mélanger le tout.",
      "Assaisonner d'huile et de citron.",
    ],
  },
  {
    id: "r32", title: "Porridge protéiné", emoji: "🥣",
    mealTypes: ["rapide", "leger"], dietTags: ["halal", "vege", "sans_lactose"],
    reqCapabilities: ["heat"], prepMinutes: 8, defaultServings: 2,
    ingredients: [
      { ingredientId: "oats", qtyPerServing: 80, unit: "g" },
      { ingredientId: "peanut_butter", qtyPerServing: 20, unit: "g" },
      { ingredientId: "honey", qtyPerServing: 15, unit: "g" },
    ],
    steps: [
      "Chauffer les flocons d'avoine avec de l'eau ou du lait 3 min.",
      "Incorporer le beurre de cacahuète.",
      "Napper de miel.",
      "Servir chaud.",
    ],
  },
  {
    id: "r33", title: "Crevettes sautées & riz", emoji: "🍤",
    mealTypes: ["proteine", "leger"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["fry"], prepMinutes: 18, defaultServings: 2,
    ingredients: [
      { ingredientId: "shrimp", qtyPerServing: 120, unit: "g" },
      { ingredientId: "rice", qtyPerServing: 90, unit: "g" },
      { ingredientId: "garlic", qtyPerServing: 2, unit: "piece" },
      { ingredientId: "green_beans", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
    steps: [
      "Cuire le riz.",
      "Saisir l'ail et les crevettes à l'huile 3 à 4 min.",
      "Ajouter les haricots verts.",
      "Servir sur le riz.",
    ],
  },
  {
    id: "r34", title: "Aubergines rôties & boulgour", emoji: "🍆",
    mealTypes: ["sain"], dietTags: ["halal", "vege", "vegan", "sans_lactose"],
    reqCapabilities: ["roast"], prepMinutes: 32, defaultServings: 2,
    ingredients: [
      { ingredientId: "eggplant", qtyPerServing: 250, unit: "g" },
      { ingredientId: "bulgur", qtyPerServing: 90, unit: "g" },
      { ingredientId: "tomato", qtyPerServing: 80, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 50, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 10, unit: "ml" },
    ],
    steps: [
      "Préchauffer le four à 200°C.",
      "Couper les aubergines, arroser d'huile et rôtir 25 min.",
      "Cuire le boulgour ; faire revenir oignon et tomate.",
      "Assembler et servir.",
    ],
  },
  {
    id: "r35", title: "Thon & pâtes express", emoji: "🐟",
    mealTypes: ["rapide", "proteine"], dietTags: ["halal", "sans_lactose"],
    reqCapabilities: ["simmer"], prepMinutes: 15, defaultServings: 2,
    ingredients: [
      { ingredientId: "pasta", qtyPerServing: 100, unit: "g" },
      { ingredientId: "tuna_canned", qtyPerServing: 100, unit: "g" },
      { ingredientId: "tomato_canned", qtyPerServing: 120, unit: "g" },
      { ingredientId: "onion", qtyPerServing: 40, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
    steps: [
      "Cuire les pâtes.",
      "Faire revenir l'oignon, ajouter tomates et thon égoutté.",
      "Mijoter 8 min.",
      "Mélanger avec les pâtes.",
    ],
  },
  {
    id: "r36", title: "Dinde grillée & purée patate douce", emoji: "🦃",
    mealTypes: ["proteine", "sain"], dietTags: ["halal", "sans_gluten", "sans_lactose"],
    reqCapabilities: ["sear"], prepMinutes: 25, defaultServings: 2,
    ingredients: [
      { ingredientId: "turkey", qtyPerServing: 150, unit: "g" },
      { ingredientId: "sweet_potato", qtyPerServing: 200, unit: "g" },
      { ingredientId: "green_beans", qtyPerServing: 100, unit: "g" },
      { ingredientId: "olive_oil", qtyPerServing: 8, unit: "ml" },
    ],
    steps: [
      "Cuire les patates douces à l'eau et les écraser en purée.",
      "Saisir les escalopes de dinde à la poêle.",
      "Faire les haricots verts vapeur.",
      "Dresser et servir.",
    ],
  },
];
